// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vyozepJ6xip7aaU4b7VPCN
// Component: UltRNsvyTIKm92
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: s6PbP_OAcqI8b0/component
import Button from "../../Button"; // plasmic-import: UBst1-0CrAf6xH/component
import ProductCard from "../../ProductCard"; // plasmic-import: qer-BTKJtG4iMx/component
import Rating from "../../Rating"; // plasmic-import: 7HssrmuA-MYOA1/component
import EmojiValueProps from "../../EmojiValueProps"; // plasmic-import: LDUJMecI5u8lbb/component
import Value from "../../Value"; // plasmic-import: cqSkO3vGyhbuAq/component
import Footer from "../../Footer"; // plasmic-import: ixdB81W5meDT3-/component

import { useScreenVariants as useScreenVariantsoDu25JF0T439S } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: oDU25jF0t4_39S/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_commerce_landing_page.module.css"; // plasmic-import: vyozepJ6xip7aaU4b7VPCN/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: UltRNsvyTIKm92/css

import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: 9R_rAz-20yK2Ml/icon
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: XlKDcLTzFzU4We/icon
import PlaneIcon from "./icons/PlasmicIcon__Plane"; // plasmic-import: q-7SFlT3UteAro/icon
import DocumentIcon from "./icons/PlasmicIcon__Document"; // plasmic-import: 1rTSeHT2s1RG6R/icon
import LockIcon from "./icons/PlasmicIcon__Lock"; // plasmic-import: A3fNHoJGfx39EI/icon
import SpeakerphoneIcon from "./icons/PlasmicIcon__Speakerphone"; // plasmic-import: JtGbGS_xkOZ4-b/icon
import MedalIcon from "./icons/PlasmicIcon__Medal"; // plasmic-import: QqGFMh72WAuDSo/icon
import LeafIcon from "./icons/PlasmicIcon__Leaf"; // plasmic-import: 9YGc9a0RGa41p2/icon
import ShoeIcon from "./icons/PlasmicIcon__Shoe"; // plasmic-import: TsJWu0SNs2LIIh/icon
import PeaceIcon from "./icons/PlasmicIcon__Peace"; // plasmic-import: G-eeP_gM77Fdy2/icon

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {
  container42?: React.ReactNode;
};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>("container42");

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<typeof NavBar>;
  container3?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  container4?: p.Flex<"div">;
  container?: p.Flex<"div">;
  emojiValueProps?: p.Flex<typeof EmojiValueProps>;
  columns?: p.Flex<"div">;
  container42?: p.Flex<"div">;
  container5?: p.Flex<"div">;
  container6?: p.Flex<"div">;
  container434?: p.Flex<"div">;
  container433?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultHomepageProps {}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsoDu25JF0T439S()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(projectcss.all, sty.section__lYoF)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              hasGap={true}
              className={classNames(projectcss.all, sty.container3)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__do2Ue)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iAje0)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"New collection!"}
                  </h1>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5I5Y4
                    )}
                  >
                    {
                      "A nam quisque orci ut vestibulum eget sem aliquet a dictumst condimentum ad quam porta a inceptos consectetur sagittis a a commodo ridiculus tempor egestas."
                    }
                  </div>
                </p.Stack>

                <Button
                  className={classNames("__wab_instance", sty.button__xesaO)}
                  colors={"black" as const}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__oEr6C)}
                      role={"img"}
                    />
                  }
                  rounded={true}
                  showEndIcon={true}
                  size={"large" as const}
                >
                  {"Shop"}
                </Button>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(projectcss.all, sty.section__jz8Do)}>
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(projectcss.all, sty.container4)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__knjxN)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__io4Ol
                  )}
                >
                  {"Featured"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button___3OguZ)}
                  colors={"link" as const}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__bfwbl)}
                      role={"img"}
                    />
                  }
                  showEndIcon={true}
                >
                  {"See more"}
                </Button>
              </div>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(projectcss.all, sty.container)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__gaqEx)}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe14.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating___12Jop)}
                    rating={"four" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ehZ9B
                  )}
                >
                  {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__f48Pa
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___4WdpX
                )}
                dollars={"79"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe15.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__kpnvf)}
                    rating={"threeHalf" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4Yvn
                  )}
                >
                  {"Nike Air Zoom Pegasus 38"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__csgE9
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__bawoM)}
                dollars={"64"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe16.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__m113)}
                    rating={"two" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___27Z6Q
                  )}
                >
                  {"Club C 85 Vintage Men's Shoes"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qsPh
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard___2HUH)}
                dollars={"99"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe17.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating___1SZiK)}
                    rating={"four" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sWpqM
                  )}
                >
                  {"Nike Air Max Genome"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dgMcJ
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__nXuC4)}
                dollars={"79"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe18.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__f3YDb)}
                    rating={"five" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__a7MEd
                  )}
                >
                  {"ULTRABOOST DNA 1.0 SHOES"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iYKyE
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                cents={"50"}
                className={classNames("__wab_instance", sty.productCard__zzlOe)}
                dollars={"65"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe19.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__ox2Lr)}
                    rating={"threeHalf" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              />
            </p.Stack>
          </section>

          <section className={classNames(projectcss.all, sty.section__aF4Sz)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___6NMg)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__phyP2)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__kPWy)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kPdwo
                    )}
                  >
                    {"Our best shoe sale of the year"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wggMb
                    )}
                  >
                    {
                      "Signature style. Unsurpassed quality and comfort. Now’s the perfect time to save on iconic shoes."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__nzkYi)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nknQc
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"3 "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"for"}
                      </span>
                      <React.Fragment>{" $169"}</React.Fragment>
                    </React.Fragment>
                  </div>

                  <Button
                    colors={"black" as const}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg__yXgcu)}
                        role={"img"}
                      />
                    }
                    rounded={true}
                    showEndIcon={true}
                    size={"large" as const}
                  >
                    {"Shop sale"}
                  </Button>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </section>

          <EmojiValueProps
            data-plasmic-name={"emojiValueProps"}
            data-plasmic-override={overrides.emojiValueProps}
            className={classNames("__wab_instance", sty.emojiValueProps)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__axAhM)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__r7AaC
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__qqMl)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__gnmsS)}
                  icon={
                    <PlaneIcon
                      className={classNames(projectcss.all, sty.svg__qRBkI)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gag6I
                    )}
                  >
                    {"Worldwide shipping"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mnwt
                    )}
                  >
                    {"Special financing and earn rewards."}
                  </div>
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__jdgUp)}>
                <Value
                  children2={
                    <Button
                      className={classNames("__wab_instance", sty.button__tCoB)}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__iDaDb)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__cQs7N)}
                  icon={
                    <DocumentIcon
                      className={classNames(projectcss.all, sty.svg__jqRh)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__u7AcK
                    )}
                  >
                    {"30-day guarantee"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tpe34
                    )}
                  >
                    {"Free return policy."}
                  </div>
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__qMiSs)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__vvQ8Q
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__h88Ub)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value___1J2J9)}
                  icon={
                    <LockIcon
                      className={classNames(projectcss.all, sty.svg__maKxL)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__arSzc
                    )}
                  >
                    {"Secured payments"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__egxmy
                    )}
                  >
                    {"We accept major credit cards."}
                  </div>
                </Value>
              </div>
            </p.Stack>
          </EmojiValueProps>

          <section className={classNames(projectcss.all, sty.section__hSxpS)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(projectcss.all, sty.container42)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ySdMm)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8BMhc
                      )}
                    >
                      {"Just added"}
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__ca2Mw
                      )}
                      colors={"link" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__msW10)}
                          role={"img"}
                        />
                      }
                      showEndIcon={true}
                    >
                      {"See more"}
                    </Button>
                  </div>
                ),

                value: args.container42
              })}
            </div>

            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(projectcss.all, sty.container5)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___3RFlj)}
              >
                <ProductCard
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe14.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__w0OX5
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0Yn93
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ud0C
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe15.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__h3MtN
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ctchn
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___0RcCh
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe16.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1SZtL
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gRoUt
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__j1Ahp
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe17.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lCv7Z
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ipAmH
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___8Gbv9
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe18.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2MDEk
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ksoGm
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__gyDlG
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe19.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                />
              </p.Stack>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__nYvjl)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(projectcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__z3Nsp)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__svQqe
                  )}
                >
                  {"Categories"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__pk2S)}
                  states={"active" as const}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kccKw
                    )}
                  >
                    {"All"}
                  </div>
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__fV8Ow)}
                >
                  {"New"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__xInA)}
                >
                  {"Womens"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__m4BSp)}
                >
                  {"Mens"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__zAPk)}
                >
                  {"Kids"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__ybyob)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iFt
                    )}
                  >
                    {"On sale"}
                  </div>
                </Button>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__aN76D)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__cxeW
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe8.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yweFr
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__riJd
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__aOdP9
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe7.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qSpfk
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__imkf5
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___7DLjz
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe6.png",
                    fullWidth: 320,
                    fullHeight: 320,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nAk5C
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aSpUk
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__c3J2
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe5.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cz19D
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5X7Jl
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__l0Mau
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe4.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wx9Ga
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gGsQd
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__j1J6
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe3.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nog2J
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1RwD7
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zjPvw
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe2.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lWywc
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eRLp
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__bRsHh
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe9.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ziApJ
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9OP8R
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__umViD
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe10.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2Tli1
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__u8CsV
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__xNmq4
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe11.png",
                    fullWidth: 766,
                    fullHeight: 766,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ersyF
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xuOtU
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__aaQho
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe12.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yZik
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tequX
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___6T8Ir
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe13.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kt6H8
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__h6Iej
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(projectcss.all, sty.section___7QEvB)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container434"}
              data-plasmic-override={overrides.container434}
              hasGap={true}
              className={classNames(projectcss.all, sty.container434)}
            >
              <Value
                center={true}
                children2={
                  <Button
                    className={classNames("__wab_instance", sty.button__qu4AZ)}
                    colors={"black" as const}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg__yanfT)}
                        role={"img"}
                      />
                    }
                    rounded={true}
                    showEndIcon={true}
                  >
                    {"Read our letter"}
                  </Button>
                }
                className={classNames("__wab_instance", sty.value___2Qooo)}
                icon={
                  <SpeakerphoneIcon
                    className={classNames(projectcss.all, sty.svg__do0N3)}
                    role={"img"}
                  />
                }
                topBottom={true}
                withButton={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xbzNp
                  )}
                >
                  {"Our goals"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fRqJi
                  )}
                >
                  {"We’re learning how to become a new kind of company."}
                </div>
              </Value>
            </p.Stack>
          </section>

          <section className={classNames(projectcss.all, sty.section__sTeJp)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container433"}
              data-plasmic-override={overrides.container433}
              hasGap={true}
              className={classNames(projectcss.all, sty.container433)}
            >
              <div className={classNames(projectcss.all, sty.column__vfDca)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__eundz
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___3OwFn
                          )}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__tylmJ)}
                  icon={
                    <MedalIcon
                      className={classNames(projectcss.all, sty.svg__mpCij)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__k4X
                    )}
                  >
                    {"We guarantee everything we sell."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__a64RG
                    )}
                  >
                    {
                      "Ad fringilla ut nisi in hendrerit malesuada nascetur a in ridiculus."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__mmC5R)}
                    colors={"link" as const}
                  >
                    {"View guarantee"}
                  </Button>
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__kgfvx)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__n8XXv
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__qc0Pr)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value___5X3Wj)}
                  icon={
                    <LeafIcon
                      className={classNames(projectcss.all, sty.svg__hYoJs)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kOuHu
                    )}
                  >
                    {"Know how your shoes are made."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tyjAn
                    )}
                  >
                    {
                      "Parturient blandit viverra blandit sem suspendisse himenaeos."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__mCLuT)}
                    colors={"link" as const}
                  />
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__zt00W)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___6KVz8
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__bxa8J)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__e0Rjd)}
                  icon={
                    <ShoeIcon
                      className={classNames(projectcss.all, sty.svg__eVKi)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xD9M3
                    )}
                  >
                    {"Keep your shoes in play."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__edHd9
                    )}
                  >
                    {
                      "Adipiscing ornare dui tellus nam nibh cum a torquent maecenas."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__zkOet)}
                    colors={"link" as const}
                  />
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__jqUrw)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__ebiWs
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__m80UL)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__mkLT)}
                  icon={
                    <PeaceIcon
                      className={classNames(projectcss.all, sty.svg__onDXp)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bbXjv
                    )}
                  >
                    {"We give back for every sale."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ouvRa
                    )}
                  >
                    {
                      "Parturient vestibulum ut a dui parturient habitant netus integer ipsum."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button___2N3MJ)}
                    colors={"link" as const}
                  />
                </Value>
              </div>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container3",
    "h1",
    "container4",
    "container",
    "emojiValueProps",
    "columns",
    "container42",
    "container5",
    "container6",
    "container434",
    "container433",
    "footer"
  ],
  navBar: ["navBar"],
  container3: ["container3", "h1"],
  h1: ["h1"],
  container4: ["container4"],
  container: ["container"],
  emojiValueProps: ["emojiValueProps", "columns"],
  columns: ["columns"],
  container42: ["container42"],
  container5: ["container5"],
  container6: ["container6"],
  container434: ["container434"],
  container433: ["container433"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  container3: "div";
  h1: "h1";
  container4: "div";
  container: "div";
  emojiValueProps: typeof EmojiValueProps;
  columns: "div";
  container42: "div";
  container5: "div";
  container6: "div";
  container434: "div";
  container433: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container3: makeNodeComponent("container3"),
    h1: makeNodeComponent("h1"),
    container4: makeNodeComponent("container4"),
    container: makeNodeComponent("container"),
    emojiValueProps: makeNodeComponent("emojiValueProps"),
    columns: makeNodeComponent("columns"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    container6: makeNodeComponent("container6"),
    container434: makeNodeComponent("container434"),
    container433: makeNodeComponent("container433"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "ShoeShop",
      description:
        "Ad ullamcorper eros nibh pharetra vulputate imperdiet consectetur vestibulum at ac posuere volutpat maecenas gravida dictum suscipit habitasse class scelerisque fermentum blandit mi a.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
